### ISSUE TITLE
Import fails systematically for the last splitted file

### ISSUE THREAD

**Issue by ghost** [rodoic/mysqldumpsplitter#3]
Hi, thanks a lot for this script. Importing in each splitted part in phpmyadmin works perfectly, except for the last part (each time, and with any db). Any idea what's going on?

**Comment by wdelfuego** [comment]
Hi Asten,

that’s the first time I hear about that! Thanks for creating an issue.

Would you be able to send me the last file, the one that fails?
I hope the data in your dump is not too sensitive for that.

Thanks, cheers!

**Comment by wdelfuego** [comment]
Closing for lack of response. If anyone else runs into this issue, do let us know so we can investigate what causes the problem.
